"""
shellstory.capture — Cross-platform shell session capture.

Generates shell hook scripts that, when sourced, log every command
to an NDJSON file as RawEvent objects.

Supported shells:
  - PowerShell (Windows / Cross-platform)
  - Bash
  - Zsh
"""

from __future__ import annotations

import os
import platform
import uuid
from datetime import datetime, timezone
from pathlib import Path

from shellstory.config import get_sessions_dir
from shellstory.models import RawEvent
from shellstory.utils.ndjson import append_event


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Hook script generators
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def generate_powershell_hook(session_id: str, capture_file: str) -> str:
    """
    Generate a PowerShell hook script that captures commands.

    The hook uses:
      - Set-PSReadLineOption -AddToHistoryHandler for pre-execution capture
      - Register-EngineEvent PowerShell.Exiting for session end
      - A prompt function wrapper to capture exit codes after execution
    """
    return f'''# ShellStory Capture Hook — PowerShell
# Session: {session_id}
# DO NOT EDIT — auto-generated by shellstory

$global:__SHELLSTORY_SESSION_ID = "{session_id}"
$global:__SHELLSTORY_CAPTURE_FILE = "{capture_file}"
$global:__SHELLSTORY_SEQ = 0

function __ShellStory_WriteEvent {{
    param([hashtable]$Event)
    $json = $Event | ConvertTo-Json -Compress -Depth 5
    # Use .NET AppendAllText to prevent PowerShell stream locking with the background daemon
    [System.IO.File]::AppendAllText($global:__SHELLSTORY_CAPTURE_FILE, $json + "`n", [System.Text.Encoding]::UTF8)
}}

# Write session_start event
$startEvent = @{{
    event_type   = "session_start"
    timestamp    = (Get-Date -Format "o")
    session_id   = $global:__SHELLSTORY_SESSION_ID
    sequence     = 0
    shell        = "powershell"
    os           = "{platform.system()}"
    hostname     = $env:COMPUTERNAME
    username     = $env:USERNAME
    env_var_names = @($env:Path -split ";" | Select-Object -First 5)
}}
__ShellStory_WriteEvent $startEvent

# Store the original prompt function
$global:__ShellStory_OriginalPrompt = $function:prompt

# Override the prompt to capture command results
function prompt {{
    $lastExit = $LASTEXITCODE
    $lastSuccess = $?

    # Get the last history entry
    $lastCmd = Get-History -Count 1 -ErrorAction SilentlyContinue
    if ($lastCmd -and $lastCmd.Id -ne $global:__SHELLSTORY_LAST_HIST_ID) {{
        $global:__SHELLSTORY_LAST_HIST_ID = $lastCmd.Id
        $global:__SHELLSTORY_SEQ++

        $exitCode = if ($lastSuccess) {{ 0 }} else {{ if ($lastExit) {{ $lastExit }} else {{ 1 }} }}
        $duration = ($lastCmd.EndExecutionTime - $lastCmd.StartExecutionTime).TotalMilliseconds

        $cmdEvent = @{{
            event_type   = "command"
            timestamp    = $lastCmd.StartExecutionTime.ToString("o")
            session_id   = $global:__SHELLSTORY_SESSION_ID
            sequence     = $global:__SHELLSTORY_SEQ
            command      = $lastCmd.CommandLine
            working_dir  = (Get-Location).Path
            exit_code    = [int]$exitCode
            duration_ms  = [int]$duration
        }}
        __ShellStory_WriteEvent $cmdEvent
    }}

    # Call original prompt
    if ($global:__ShellStory_OriginalPrompt) {{
        & $global:__ShellStory_OriginalPrompt
    }} else {{
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
    }}
}}

# Capture session end on exit
Register-EngineEvent PowerShell.Exiting -Action {{
    $global:__SHELLSTORY_SEQ++
    $endEvent = @{{
        event_type = "session_end"
        timestamp  = (Get-Date -Format "o")
        session_id = $global:__SHELLSTORY_SESSION_ID
        sequence   = $global:__SHELLSTORY_SEQ
    }}
    __ShellStory_WriteEvent $endEvent
}} | Out-Null

Write-Host "[shellstory] Capture active. Session: $($global:__SHELLSTORY_SESSION_ID.Substring(0,8))..." -ForegroundColor Green
'''


def generate_bash_hook(session_id: str, capture_file: str) -> str:
    """
    Generate a Bash hook script that captures commands.

    Uses PROMPT_COMMAND to fire after every command execution.
    """
    return f'''# ShellStory Capture Hook — Bash
# Session: {session_id}
# DO NOT EDIT — auto-generated by shellstory

export __SHELLSTORY_SESSION_ID="{session_id}"
export __SHELLSTORY_CAPTURE_FILE="{capture_file}"
export __SHELLSTORY_SEQ=0

__shellstory_write_event() {{
    echo "$1" >> "$__SHELLSTORY_CAPTURE_FILE"
}}

# Write session_start event
__shellstory_write_event '{{"event_type":"session_start","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'","session_id":"'{session_id}'","sequence":0,"shell":"bash","os":"'$(uname -s)'","hostname":"'$(hostname)'","username":"'$(whoami)'"}}'

__shellstory_preexec() {{
    export __SHELLSTORY_CMD_START=$(date +%s%3N 2>/dev/null || python3 -c "import time; print(int(time.time()*1000))")
    export __SHELLSTORY_LAST_CMD="$1"
}}

__shellstory_precmd() {{
    local exit_code=$?
    if [ -n "$__SHELLSTORY_LAST_CMD" ]; then
        __SHELLSTORY_SEQ=$(( __SHELLSTORY_SEQ + 1 ))
        local now=$(date +%s%3N 2>/dev/null || python3 -c "import time; print(int(time.time()*1000))")
        local duration=$(( now - __SHELLSTORY_CMD_START ))
        local timestamp=$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)
        local cmd=$(echo "$__SHELLSTORY_LAST_CMD" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read().strip())[1:-1])" 2>/dev/null || echo "$__SHELLSTORY_LAST_CMD")
        local wd=$(pwd)

        __shellstory_write_event '{{"event_type":"command","timestamp":"'"$timestamp"'","session_id":"'"$__SHELLSTORY_SESSION_ID"'","sequence":'"$__SHELLSTORY_SEQ"',"command":"'"$cmd"'","working_dir":"'"$wd"'","exit_code":'"$exit_code"',"duration_ms":'"$duration"'}}'
        unset __SHELLSTORY_LAST_CMD
    fi
}}

# Install hooks
if [ -n "$BASH_VERSION" ]; then
    # Use bash-preexec if available, otherwise fallback to DEBUG trap
    if type preexec &>/dev/null 2>&1; then
        preexec() {{ __shellstory_preexec "$1"; }}
        precmd() {{ __shellstory_precmd; }}
    else
        trap '__shellstory_preexec "$BASH_COMMAND"' DEBUG
        PROMPT_COMMAND="__shellstory_precmd;${{PROMPT_COMMAND}}"
    fi
fi

echo "[shellstory] Capture active. Session: ${{__SHELLSTORY_SESSION_ID:0:8}}..."
'''


def generate_zsh_hook(session_id: str, capture_file: str) -> str:
    """Generate a Zsh hook script using preexec/precmd hooks."""
    # Zsh has native preexec/precmd support
    return f'''# ShellStory Capture Hook — Zsh
# Session: {session_id}

export __SHELLSTORY_SESSION_ID="{session_id}"
export __SHELLSTORY_CAPTURE_FILE="{capture_file}"
export __SHELLSTORY_SEQ=0

__shellstory_write_event() {{
    echo "$1" >> "$__SHELLSTORY_CAPTURE_FILE"
}}

__shellstory_write_event '{{"event_type":"session_start","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)'","session_id":"'{session_id}'","sequence":0,"shell":"zsh","os":"'$(uname -s)'","hostname":"'$(hostname)'","username":"'$(whoami)'"}}'

__shellstory_preexec() {{
    export __SHELLSTORY_CMD_START=$(($(date +%s) * 1000))
    export __SHELLSTORY_LAST_CMD="$1"
}}

__shellstory_precmd() {{
    local exit_code=$?
    if [ -n "$__SHELLSTORY_LAST_CMD" ]; then
        __SHELLSTORY_SEQ=$(( __SHELLSTORY_SEQ + 1 ))
        local now=$(($(date +%s) * 1000))
        local duration=$(( now - __SHELLSTORY_CMD_START ))
        local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        local cmd=$(echo "$__SHELLSTORY_LAST_CMD" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read().strip())[1:-1])" 2>/dev/null || echo "$__SHELLSTORY_LAST_CMD")

        __shellstory_write_event '{{"event_type":"command","timestamp":"'"$timestamp"'","session_id":"'"$__SHELLSTORY_SESSION_ID"'","sequence":'"$__SHELLSTORY_SEQ"',"command":"'"$cmd"'","working_dir":"'"$(pwd)"'","exit_code":'"$exit_code"',"duration_ms":'"$duration"'}}'
        unset __SHELLSTORY_LAST_CMD
    fi
}}

autoload -Uz add-zsh-hook
add-zsh-hook preexec __shellstory_preexec
add-zsh-hook precmd __shellstory_precmd

echo "[shellstory] Capture active. Session: ${{__SHELLSTORY_SESSION_ID[1,8]}}..."
'''


def detect_shell() -> str:
    """Detect the current shell type."""
    if platform.system() == "Windows":
        # Check if we're in PowerShell
        if os.environ.get("PSModulePath"):
            return "powershell"
        return "cmd"

    shell = os.environ.get("SHELL", "").lower()
    if "zsh" in shell:
        return "zsh"
    if "bash" in shell:
        return "bash"
    return "bash"  # default


def create_hook_file(session_id: str, capture_file: str, shell_type: str, sessions_dir: Path) -> Path:
    """
    Write the appropriate shell hook script to disk.

    Returns the path to the generated hook file.
    """
    sessions_dir.mkdir(parents=True, exist_ok=True)

    generators = {
        "powershell": generate_powershell_hook,
        "bash": generate_bash_hook,
        "zsh": generate_zsh_hook,
    }

    generator = generators.get(shell_type)
    if not generator:
        raise ValueError(
            f"Unsupported shell type: {shell_type}. "
            f"Supported: {', '.join(generators.keys())}"
        )

    ext = ".ps1" if shell_type == "powershell" else ".sh"
    hook_path = sessions_dir / f"{session_id}_hook{ext}"
    script = generator(session_id, capture_file)

    with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(script)

    return hook_path


def write_session_start_event(capture_file: Path, session_id: str, shell_type: str) -> None:
    """Write the initial session_start event to the capture file (Python-side fallback)."""
    event = RawEvent(
        event_type="session_start",
        timestamp=datetime.now(timezone.utc),
        session_id=session_id,
        sequence=0,
        shell=shell_type,
        os=platform.system(),
        hostname=platform.node(),
        username=os.environ.get("USERNAME") or os.environ.get("USER", "unknown"),
    )
    append_event(capture_file, event.model_dump(mode="json"))
