"""
shellstory.connectors — Output connectors for exporting runbooks.

Connectors transform a Runbook model into a specific output format
and write it to the target destination.

Supported:
  - Markdown: Local .md files (default)
  - (Future: Notion, Obsidian, Confluence)
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from shellstory.models import Runbook

logger = logging.getLogger(__name__)


class BaseConnector(ABC):
    """Abstract base for output connectors."""

    @abstractmethod
    def export(self, runbook: Runbook, config: dict[str, Any]) -> str:
        """Export runbook and return the path/URL of the result."""
        ...


class MarkdownConnector(BaseConnector):
    """Export runbook as a professional Markdown file."""

    def export(self, runbook: Runbook, config: dict[str, Any]) -> str:
        """Export the runbook to a Markdown file, plus a -raw transcript."""
        # 1. Export the beautiful Runbook
        out_dir = Path(config.get("connectors", {}).get("markdown", {}).get("output_dir", "~/runbooks")).expanduser()
        out_dir.mkdir(parents=True, exist_ok=True)
        
        safe_title = "".join(
            c if c.isalnum() or c in "-_ " else "" for c in runbook.title
        ).strip().replace(" ", "-").lower()
        if not safe_title:
            safe_title = runbook.session_id[:8]
            
        out_path = out_dir / f"{safe_title}.md"
        
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(f"# {runbook.title}\n\n")
            f.write(f"{runbook.description}\n\n")
            
            f.write(f"*Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*\n")
            f.write(f"*Session: {runbook.session_id[:8]}...*\n\n")
            
            if runbook.prerequisites:
                f.write("## Prerequisites\n")
                for p in runbook.prerequisites:
                    f.write(f"- **{p.name}**")
                    if p.version_constraint:
                        f.write(f" (v{p.version_constraint})")
                    if p.how_to_check:
                        f.write(f": Check via `{p.how_to_check}`")
                    f.write("\n")
                f.write("\n")
                
            if runbook.variables:
                f.write("## Environment Variables\n")
                for v in runbook.variables:
                    f.write(f"- `{v.variable_name}`: {v.original_pattern}. Setup: `{v.how_to_set}`\n")
                f.write("\n")
                
            f.write("## Steps\n")
            for step in sorted(runbook.steps, key=lambda s: s.step_number):
                f.write(f"### Step {step.step_number}: {step.title}\n")
                f.write(f"{step.explanation}\n\n")
                f.write(f"```bash\n{step.command}\n```\n")
                if getattr(step, 'warning', None):
                    f.write(f"> **Warning:** {step.warning}\n\n")
                
            if runbook.errors_and_fixes:
                f.write("## Troubleshooting\n")
                for e in runbook.errors_and_fixes:
                    f.write(f"### ❌ Error during: `{e.failed_command}`\n")
                    f.write(f"- **Exit Code:** {e.exit_code}\n")
                    if e.error_output:
                        f.write(f"- **Output:** `{e.error_output}`\n")
                    if e.final_fix:
                        f.write(f"- **Fix:** Run `{e.final_fix}`\n")
                    if e.lesson:
                        f.write(f"- **Note:** {e.lesson}\n")
                    f.write("\n")
                    
            f.write("---\n*Generated by ShellStory*\n")

        # 2. Export the Raw Transcript
        raw_path = out_dir / f"{safe_title}-raw.md"
        from shellstory.config import get_sessions_dir
        from shellstory.utils.ndjson import load_events
        
        try:
            sessions_dir = get_sessions_dir(config)
            ndjson_file = sessions_dir / f"{runbook.session_id}.ndjson"
            if ndjson_file.exists():
                events = load_events(ndjson_file)
                with open(raw_path, "w", encoding="utf-8") as rf:
                    rf.write(f"# {runbook.title} - Raw Transcript\n\n")
                    for ev in events:
                        if ev.event_type == "command" and ev.command:
                            status = "❌" if ev.exit_code != 0 else "✅"
                            rf.write(f"[{status}] `{ev.command}`\n")
                            if ev.duration_ms:
                                rf.write(f"  *Duration: {ev.duration_ms}ms*\n")
        except Exception as e:
            logger.warning(f"Failed to generate raw transcript: {e}")

        return str(out_path)


def get_connector(name: str) -> BaseConnector:
    """Get a connector by name."""
    connectors = {
        "markdown": MarkdownConnector(),
    }
    if name not in connectors:
        raise ValueError(
            f"Unknown connector '{name}'. Available: {', '.join(connectors.keys())}"
        )
    return connectors[name]
